#!/usr/bin/env ruby

test_files = ["arrays", "files", "strings", "hashes", "ranges"]

if ARGV[0] == "-h" || ARGV[0] == "--help" then
  print "\noptions:\n"
  test_files.each {|s| puts "  * " + s }
  puts
elsif ARGV[0] == "-s" then
  ARGV.shift
  puts
  puts "All(Summary):"
  test_files.each do |file|
    require File.expand_path(File.dirname(__FILE__) + "/test_#{file}.rb")
  end
else
  test_files = ARGV unless ARGV.length == 0
  test_files.each do |file|
    puts
    puts "#{file.capitalize}: "
    path = File.expand_path(File.dirname(__FILE__) + "/test_#{file}.rb")
    command = "ruby #{path}"
    test_results = `#{command}`
    test_results.each_line do |line|
      puts "  " + line
    end
  end
end